### ISSUE TITLE
testshib.org problem

### ISSUE THREAD

**Issue by ptman** [russellhaering/gosaml2#20]
I got the following error from [RetrieveAssertionInfo](https://godoc.org/github.com/russellhaering/gosaml2#SAMLServiceProvider.RetrieveAssertionInfo) when testing with testshib.org:

    error validating response: Missing signature referencing the top-level element

**Comment by phoebesimon** [comment]
@ptman could you provide a little more info, please? The AssertionInfo that it's trying to validate would be especially helpful for understanding the problem

**Comment by Resisty** [comment]
Hello, I think I'm experiencing a similar problem. When trying to retrieve the assertion info:
`assertionInfo, err := sp.RetrieveAssertionInfo(r.FormValue("SAMLResponse"))`
the program throws the error:
```
2017/02/10 17:22:33 http: panic serving [::1]:56367: missing AttributeStatement element
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc4201c6a00)
	/usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:1491 +0x12a
panic(0x3acf40, 0xc4202384e0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:458 +0x243
main.main.func1(0x586f40, 0xc42010e750, 0xc4200d2960)
	/Users/brian.auron/go/src/main.go:103 +0x5b7
net/http.HandlerFunc.ServeHTTP(0x41f8b8, 0x586f40, 0xc42010e750, 0xc4200d2960)
	/usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0x5a54e0, 0x586f40, 0xc42010e750, 0xc4200d2960)
	/usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420076a80, 0x586f40, 0xc42010e750, 0xc4200d2960)
	/usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4201c6a00, 0x587600, 0xc4201c4640)
	/usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2293 +0x44d
```

I'm not sure what is going wrong, dumping the request out shows what appears to be an encoded response for `SAMLResponse` as in [RetrieveAssertionInfo](https://godoc.org/github.com/russellhaering/gosaml2#SAMLServiceProvider.RetrieveAssertionInfo)

**Comment by russellhaering** [comment]
@ptman I believe this should be resolved now, can you re-test?

**Comment by ptman** [comment]
Still getting the same result. I'll see if I can prepare a testcase. Have you tried testshib.org?

**Comment by ptman** [comment]
Can you get the same error using: https://gist.github.com/ptman/102629ca9aded1c2db0d45968dc998ed

**Comment by ptman** [comment]
https://stackoverflow.com/questions/45193627/no-providerid-parameter-given-in-shibboleth-sso-authentication-request-from-te helped me

**Comment by ptman** [comment]
So I actually got testshib.org working with the current master.

**Comment by ptman** [comment]
Now I'm having trouble with testshib.org again. It doesn't find metadata even though I successfully uploaded it. But at the same time I've had success with Azure AD SAML (ADFS?)
